<div class="  item-categories pull-left">
	<h4 class="title">Categories</h4>
	<ul class="nav nav-pills nav-stacked">
		 <li><a href="/categories/onhand">Onhand Items</a></li>
		 <li><a href="/categories/soap">Soaps</a></li>
		 <li><a href="/categories/gadgets">Gadgets</a></li>
		 <li><a href="/categories/bags">Bags</a></li>
		 <li><a href="/categories/dress">Dresses</a></li>
		 <li><a href="/categories/skirts">Shorts&Skirts</a></li>
		 <li><a href="/categories/pants">Pants</a></li>
		 <li><a href="/categories/tops">Tops/Loose Tops</a></li>
		 <li><a href="/categories/pullovers">Longsleeves</a></li>
		 <li><a href="/categories/jackets">Cardigans</a></li>
		 <li><a href="/categories/jumpshorts">Jumpsuits</a></br></li>
	</ul>
</div>
<div class="cat-album">
	<h2 class="title"><?php echo ucfirst($category).'<br/>'; ?></h2>
	<p class="title"><?php echo ucfirst($category).'<br/>'; ?></p>
	<?php
		foreach ($items as $key => $item):
	?><div class="pic-album">
		<div class="picture" id="<?php echo $item['product_id'] ?>">
		<img src="<?php echo $item['product_image'] ?>" class="picture-inner"></br>
		<?php echo $item['product_name'].'<br/>'.'Php '.$item['price'].'<br/>'; ?>
		<button class="btn btn-sm btn-danger">
			<span class="glyphicon glyphicon-heart-empty"></span> Add to Cart
		</button>
		</div>
	</div>
	<?php
	endforeach;
	?>
</div>
<div class="pull-right">
	<a href="/cart"><button class="btn btn-lg btn-warning">View Cart</button></a>
</div>
<script type="text/javascript">
	jQuery(function($){
		$(".btn-danger").on("click",function(){
			$.ajax({
				type: "POST",
				url: "index",
				data: {id: $(this).parent().attr("id")}
			}).done(function(){
				alert("Successfully added item!");
			}).fail(function(){
				alert("Unable to add item!")
			});
		});
	});
</script>