<a href="/admin?logout=1"><button>Log Out</button></a> &nbsp;
<a href="add">Add Items</a> &nbsp;
<a href="products">View/Edit Products</a> &nbsp;
<a href="admin">Home</a>
<div class="success">Successfully added item!</div>
<form method="POST" enctype="multipart/form-data">
	<img class="picture-inner" style="display: none;"/></br>
	<input type="file" name="file"/>
	<div class="image error">
		Please choose an image to be uploaded
	</div><br/>
	<div class="invalid-image error">
		The file chosen is not an image
	</div><br/>
	Item Description<br/>
	<input type="text" name="description"/><br/>
	<div class="description error">
		Please specify an item description
	</div><br/>
	Item Price<br/>
	<input type="text" name="price"/><br/>
	<div class="price error">
		Please specify an item price
	</div><br/>
	<div class="invalid-price error">
		Please specify a valid positive item price without commas
	</div><br/>
	<div class="stocks" style="display:none">
		Item Quantity<br/>
		<input type="text" name="stocks"/><br/>
		<div class="stocks-error error">
			Please specify an item quantity
		</div><br/>
		<div class="invalid-stocks error">
			Please specify a valid positive item quantity
		</div><br/>
	</div>
	Item Category<br/>
	<select name="category">
		<option value="dress">Dress</option>
		<option value="gadgets">Gadgets</option>
		<option value="jackets">Jackets</option>
		<option value="jumpshorts">Jumpshorts</option>
		<option value="onhand">Onhand Items</option>
		<option value="pullovers">Pullovers</option>
		<option value="shirts">Shirts</option>
		<option value="skirts">Skirts</option>
		<option value="soap">Soap</option>
		<option value="tops">Tops</option>
		<option value="bags">Bags</option>
		<option value="pants">Pants</option>
	</select>
	<button class="btn-success btn submit" type="submit">Submit</button>
</form>
<script type="text/javascript">
	jQuery(function($) {
		$(".submit").on("click", function(e) {
			e.preventDefault();
			var error = false;
			$(".error").hide();
			if ($("input[type='file']")[0].files.length == 0) {
				$(".image").show();
				error = true;
			}
			if ($("input[name='description']").val().trim() == "") {
				$(".description").show();
				error = true;
			}
			if ($("input[name='price']").val().trim() == "") {
				$(".price").show();		
				error = true;
			}
			else if ($("input[name='price']").val().trim().search(/[^.0-9]/) != -1 || isNaN($("input[name='price']").val().trim())) {
				$(".invalid-price").show();		
				error = true;
			}
			if ($("input[name='stocks']").val().trim() == "") {
				if ($("select").val() == "onhand"){
					$(".stocks-error").show();		
					error = true;
				}
			}
			else if ($("input[name='stocks']").val().trim().search(/[^0-9]/) != -1 || isNaN($("input[name='stocks']").val().trim())) {
				if ($("select").val() == "onhand"){
					$(".invalid-stocks").show();		
					error = true;
				}
			}
			if (!error) {
				var fd = new FormData();
				fd.append("image",$(this).parent().find("input[type='file']")[0].files[0]);
				fd.append("description",$(this).parent().find("input[name='description']").val());
				fd.append("price",$(this).parent().find("input[name='price']").val());
				fd.append("stocks",$(this).parent().find("input[name='stocks']").val());
				fd.append("category",$(this).parent().find("select").val());
				$(".success").show();
				$(".picture-inner").hide();
				$(".stocks").hide();
				$(this).parent().trigger("reset");
				$(this).replaceWith($(this).val("").clone(true));
				$.ajax({
					type: "POST",
					url: "add",
					data: fd,
		            processData: false,
		            contentType: false
				});
			}
		});
		$("input[type='file']").on("change", function() {
			if ($(this)[0].files[0].type.search(/jpeg|png|gif/) == -1) {
				$(".invalid-image").show();		
				$(this).replaceWith($(this).val("").clone(true));
				$(".picture-inner").hide();
			}
			else {
				var reader = new FileReader();
	            reader.onload = function (e) {
	                $(".picture-inner").attr("src", e.target.result).css("display","inline");
	            };
	            reader.readAsDataURL($(this)[0].files[0]);
				$(".invalid-image").hide();		
			}
		});
		$("select").on("change", function(){
			$(".stocks").hide();
			$(".stocks input[name='stocks']").val("");
			$(".error").hide();
			if ($("select").val() == "onhand"){
				$(".stocks").show();
			}
		});
	});
</script>