<a href="/admin?logout=1"><button>Log Out</button></a>
<form method="POST" enctype="multipart/form-data">
	<input type="file" name="file"/>
	Item Description<br/>
	<input type="text" name="description"/><br/>
	Item Price<br/>
	<input type="text" name="price"/><br/>
	Item Category<br/>
	<select name="category">
		<option value="dress">Dress</option>
		<option value="gadgets">Gadgets</option>
		<option value="jackets">Jackets</option>
		<option value="jumpshorts">Jumpshorts</option>
		<option value="onhand">Onhand Items</option>
		<option value="pullovers">Pullovers</option>
		<option value="shirts">Shirts</option>
		<option value="skirts">Skirts</option>
		<option value="soap">Soap</option>
		<option value="tops">Tops</option>
		<option value="bags">Bags</option>
		<option value="pants">Pants</option>
	</select>
	<button class="btn-success btn submit" type="submit">Submit</button>
</form>
<script type="text/javascript">
	jQuery(function($) {
		$(".submit").on("click", function(e) {
			if ($("input[type='file']")[0].files.length == 0) {
				alert("Please choose an image to be uploaded");
				e.preventDefault();
			}
			else if ($("input[name='description']").val().trim() == "") {
				alert("Please specify an item description");
				e.preventDefault();
			}
			else if ($("input[name='price']").val().trim() == "") {
				alert("Please specify an item price");
				e.preventDefault();
			}
			else if ($("input[name='price']").val().trim().search(/[^.0-9]/) != -1 || isNaN($("input[name='price']").val().trim())) {
				alert("Please specify a valid positive item price");
				e.preventDefault();
			}
			else {
				alert("Successfully added item!");
			}
		});
		$("input[type='file']").on("change", function() {
			if ($(this)[0].files[0].type.search(/jpeg|png|gif/) == -1) {
				alert("Chosen file is not an image!");
				$(this).replaceWith($(this).val("").clone(true));
			}
		});
	});
</script>