<div class="container2">
	<div class="row">
		<div class="col-xs-12 col-md-8">
			<h4 class="pull-left"> Hi Admin!</h4>
			<a href="/admin?logout=1" role="button" class="btn btn-info btn-sm pull-right"><span class="glyphicon glyphicon-off"></span> Log Out</a> 
		</div>
	</div>
	<div class="row">
		<div class="col-sm-3 border-right item-categories">
			<ul class="nav nav-tabs nav-stacked">
				<li class="active"><a href="admin">Home</a></li>
			  	<li><a href="add">Add Items</a></li>
				<li><a href="products">View/Edit Products</a></li>
				<li><a href="feedbacks">Feedbacks</a></li>
				<li><a href="bogusbuyers">Bogus Buyers</a></li>
			</ul>
		</div>
		<div class="col-sm-7">
			<h4>Transactions</h4>
		</div>
	</div>
</div>