<div class="album">
	<h2>Bogus buyers</h2>
    <div class="row pull-left">
		  <div class="col-sm-4 col-md-4">
		    <div class="thumbnail">
				<img src="\images\bpi.jpg">
		    </div>
		  </div>
	<!-- </div>
	 <div class="row pull-left">
 -->		  <div class="col-sm-4 col-md-4">
		    <div class="thumbnail">
				<img src="\images\bpi.jpg">
		    </div>
		  </div>
	<!--</div> 
	 <div class="row pull-left"> -->
		  <div class="col-sm-4 col-md-4">
		    <div class="thumbnail">
				<img src="\images\bpi.jpg">
		    </div>
		  </div>
		  <div class="col-sm-4 col-md-4">
		    <div class="thumbnail">
				<img src="\images\bpi.jpg">
		    </div>
		  </div>
	</div>
</div>