<div class="album">
	<div class="page-header">
		<h2>Shopping Cart</h2>
		<h5>Selected items</h5>
		<a href="/order" class="btn btn-lg btn-success" role="button">
			<span class="glyphicon glyphicon-ok-circle"></span>Checkout
		</a>
		<a href="/categories/pants" class="btn btn-lg btn-warning pull-right" role="button">
			<span class="glyphicon glyphicon-plus"></span>Shop More!
		</a>
	</div>
	<div class="album-inner">
		<?php foreach ($items as $key => $item): ?>
			<div class="picture" id="<?php echo $item['product_id'] ?>">
				<img src="<?php echo $item['product_image'] ?>" class="picture-inner">
				<p><?php echo $item['product_name'].'<br/>'; ?></p>
				<button class="btn btn-info">Remove from Cart</button>
			</div>
		<?php endforeach ?>
	</div>
</div>
<script type="text/javascript">
	jQuery(function($){
		$(".btn").on("click", function(){
			$.ajax({
				type: "POST",
				url: "index",
				data: {remove: $(this).parent().attr("id")},
			}).done(function(){
				alert("Successfully removed item!");
			}).fail(function(){
				alert("Unable to remove item!")
			});
			$(this).parent().remove();
		});
	});
</script>