<div class="album">
	<div class="page-header">
		<center>
			<h3>Shopping Cart</h3>
			<strong>Selected items</strong>
		</center>
	</div>
	<div class="album-inner">
		<?php foreach ($items as $key => $item): ?>
			<div class="picture" id="<?php echo $item['product_id'] ?>">
				<img src="<?php echo $item['product_image'] ?>" class="picture-inner">
				<p><?php echo $item['product_name'].'<br/>'; ?></p>
				<button class="btn btn-info">Remove from Cart</button>
			</div>
		<?php endforeach ?>
	</div>
</div>
<a href="/order"><button class="btn btn-success">Checkout</button></a>
<a href="/categories/pants"><button class="btn btn-warning">Shop More!</button></a>
<script type="text/javascript">
	jQuery(function($){
		$(".btn").on("click", function(){
			$.ajax({
				type: "POST",
				url: "index",
				data: {remove: $(this).parent().attr("id")},
			}).done(function(){
				alert("Successfully removed item!");
			}).fail(function(){
				alert("Unable to remove item!")
			});
			$(this).parent().remove();
		});
	});
</script>