<div class="album">
	<div class="page-header">
		<center>
			<h3>Shopping Cart</h3>
			<strong>Selected items</strong>
		</center>
	</div>
	<div class="album-inner">
		<div class="picture">
			<img src="\images\logo.jpg" class="picture-inner">
			<p>Text1</p>
			<button class="btn btn-info">Remove from Cart</button>
		</div>
		<div class="picture">
			<img src="\images\logo.jpg" class="picture-inner">
			<p>Text1</p>
			<button class="btn btn-info">Remove from Cart</button>
		</div>
		<div class="picture">
			<img src="\images\logo.jpg" class="picture-inner">
			<p>Text1</p>
			<button class="btn btn-info">Remove from Cart</button>
		</div>
	</div>
</div>