<div class="album">
	<h2>Proofs of Purchase and Satisfied Customers</h2>
	<div class="album-inner">
		<?php foreach ($transactions as $key => $transaction): ?>
			<div class="picture">
				<img src="\images\day.jpg" class="picture-inner">
				<h5>Customer:</h5>
					<h6>Diannara M. Calamares</h6>
				<h5>Feedback:</h5>
					<h6>"It works!"</h6>
			</div>
		<?php endforeach;?>
	</div>
</div>