<div class="album">
	<h2>Proofs of Purchase and Satisfied Customers</h2>
	<div class="album-inner">
	<div class="picture">
			<img src="\images\day.jpg" class="picture-inner">
			<h5>Customer:</h5>
				<h6>Diannara M. Calamares</h6>
			<h5>Feedback:</h5>
				<h6>"It works!"</h6>
		</div>
		<div class="picture">
			<img src="\images\sel.jpg" class="picture-inner">
			<h5>Customer:</h5>
				<h6>Krissel Sibayan</h6>
			<h5>Feedback:</h5>
				<h6>"It's beautiful"</h6>
		</div>
		<div class="picture">
			<img src="\images\jas.jpg" class="picture-inner">
			<h5>Customer:</h5>
				<h6>Jasmine Caceres</h6>
			<h5>Feedback:</h5>
				<h6>"It looks good on me!"</h6>
		</div>
	</div>
</div>