<div class="container2">
	<div class="row">
		<div class="col-xs-12 col-md-8">
			<h4 class="pull-left"> Hi Admin!</h4>
			<a href="/admin?logout=1" role="button" class="btn btn-info btn-sm pull-right"><span class="glyphicon glyphicon-off"></span> Log Out</a> 
		</div>
	</div>
	<div class="row">
		<div class="col-sm-3 border-right item-categories">
			<ul class="nav nav-tabs nav-stacked">
				<li><a href="admin">Home</a></li>
			  	<li><a href="add">Add Items</a></li>
				<li><a href="products">View/Edit Products</a></li>
				<li class="active"><a href="feedbacks">Feedbacks</a></li>
				<li><a href="bogusbuyers">Bogus Buyers</a></li>
			</ul>
		</div>
		<div class="col-sm-7">
			<div class="success alert alert-success alert-dismissible" role="alert">
			  <button type="button" class="close" data-dismiss="alert">
			  	<span aria-hidden="true">&times;</span>
			  	<span class="sr-only">Close</span></button>
			  <strong>Success!</strong> You've successfully addedd an item!
			</div>
					<h5>Add a Feedback from a Customer</h5></br>
				<form method="POST" enctype="multipart/form-data">
					<div class="image error alert alert-danger alert-dismissible" role="alert">
					  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					  <strong>Warning!</strong> Please choose a file to upload!
					</div>
					<div class="invalid-image error alert alert-danger alert-dismissible" role="alert">
					  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					  <strong>Warning!</strong>The file chosen is not an image
					</div>
					<img class="picture-inner" style="display: none;"/></br>
					<input type="file" name="file" class="btn-file"/></br>
				<button class="btn-success btn submit" type="submit">
					<span class="glyphicon glyphicon-send"></span> Submit
				</button>
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">
	jQuery(function($) {
		$(".submit").on("click", function(e) {
			e.preventDefault();
			var error = false;
			$(".error").hide();
			if ($("input[type='file']")[0].files.length == 0) {
				$(".image").show();
				error = true;
			}
			if (!error) {
				var fd = new FormData();
				fd.append("image",$(this).parent().find("input[type='file']")[0].files[0]);
				$(".success").show();
				$(".picture-inner").hide();
				$(".stocks").hide();
				$(this).parent().trigger("reset");
				$(this).replaceWith($(this).val("").clone(true));
				$.ajax({
					type: "POST",
					url: "feedbacks",
					data: fd,
		            processData: false,
		            contentType: false
				});
			}
		});
		$("input[type='file']").on("change", function() {
			if ($(this)[0].files[0].type.search(/jpeg|png|gif/) == -1) {
				$(".invalid-image").show();		
				$(this).replaceWith($(this).val("").clone(true));
				$(".picture-inner").hide();
			}
			else {
				var reader = new FileReader();
	            reader.onload = function (e) {
	                $(".picture-inner").attr("src", e.target.result).css("display","inline");
	            };
	            reader.readAsDataURL($(this)[0].files[0]);
				$(".invalid-image").hide();		
			}
		});
	});
</script>