<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
	  <ol class="carousel-indicators">
	    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
	    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
	    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
	  </ol>

	  <!-- Wrapper for slides -->
	  <center>
	  	<div class="carousel-inner">
	  	  <div class="item active">
	    	  <img src="images/fb.jpg" alt="...">
		      <div class="carousel-caption">
		      </div>
	    </div>
	    <div class="item">
	    	  <img src="images/fb.jpg" alt="...">
		      <div class="carousel-caption">
		        ...
		      </div>
	    </div>
	    <div class="item">
	    	  <img src="images/fb.jpg" alt="...">
		      <div class="carousel-caption">
		        ...
		      </div>
	    </div>
	  </div>
	   	</center>

	  <!-- Controls -->
	  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
	    <span class="glyphicon glyphicon-chevron-left"></span>
	  </a>
	  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
	    <span class="glyphicon glyphicon-chevron-right"></span>
	  </a>
</div>
<div class="banner">
    <p>
    	<a href="/categories/onhand" class="btn btn-lg btn-primary" role="button">
    	<span class="glyphicon glyphicon-shopping-cart"></span>
    	Shop Now!
   		</a>
   	</p>
</div>
<div class="mid">
	<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
         Bogus Buyers
        </a>
      </h2>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body">
        <!-- thumbnail -->
        <div class="row">
		  <div class="col-sm-2 col-md-2">
		    <div class="thumbnail">
				<img src="\images\bpi.jpg">	
		      <div class="caption">
		      </div>
		    </div>
		  </div>
		</div>
		<!-- endthumbnails -->
      </div>
    <p>
    	<a href="\bogus" class="btn btn-primary" role="button">
    		<span class="glyphicon glyphicon-expand"></span>Show More
    	</a>
    </p>
    </div>
  </div>  
</div>
</div>