<div class="jumbotron">
	<div class="style">
		<h1>Check it out!</h1>
		<p>Grab your very own printed jumpsuits for a fabulous outfit for every occasion!</p>
		<center>
		<img src="\images\pants.jpeg" class="jumbotron-img">	
			<a href="\categories\pants">
			<button class="btn btn-lg btn-danger">
				<span class="glyphicon glyphicon-shopping-cart"></span>Shop Now!
			</button>
			</a>
		</center>
	</div>
</div>
<div class="mid">
	<hr class="line hr">
	<div class="categories">
		<h2 class="title">Categories</h2>
			<a href="/categories/onhand">Onhand Items</a>
			<a href="/categories/soap">Soaps</a>
			<a href="/categories/gadgets">Gadgets</a>
			<a href="/categories/bags">Bags</a>
			<a href="/categories/dress">Dresses</a>
			<a href="/categories/skirts">Shorts/Skirts/Denim</a>
			<a href="/categories/pants">Pants/Jeggings/Harem Pants</a>
			<a href="/categories/tops">Tops/Loose Tops</a>
			<a href="/categories/pullovers">Pullovers/Longsleeves</a>
			<a href="/categories/jackets">Jackets/Cardigans/Blazers</a>
			<a href="/categories/jumpshorts">Jumpshorts/Jumpsuits</a></br>
	</div>
	<div class="bogus buyers"></div>
</div>