<div class="jumbotron">
	<div class="style">
		<h1>Check it out!</h1>
		<p>Grab your very own printed jumpsuits for a fabulous outfit for every occasion!</p>
		<center>
		<img src="\images\pants.jpeg" class="jumbotron-img">	
			<a href="\pants">
			<button class="btn btn-lg btn-danger">Shop Now!</button>
			</a>
		</center>
	</div>
</div>
<div class="mid">
	<hr class="line hr">
	<div class="categories">
		<h2 class="title">Categories</h2>
			<a href="\onhand">Onhand Items</a>
			<a href="\soap">Soaps</a>
			<a href="\gadget">Gadgets</a>
			<a href="\bag">Bags</a>
			<a href="\dress">Dresses</a>
			<a href="\skirts">Shorts/Skirts/Denim</a>
			<a href="\pants">Pants/Jeggings/Harem Pants</a>
			<a href="\tops">Tops/Loose Tops</a>
			<a href="\pullovers">Pullovers/Longsleeves</a>
			<a href="\jackets">Jackets/Cardigans/Blazers</a>
			<a href="\jumpshorts">Jumpshorts/Jumpsuits</a></br>
	</div>
	<div class="bogus buyers"></div>
</div>