<div class="or-container">
	<div class="form">
		<form method="POST">
			<?php if (isset($invalid)):?>
				<div class="alert alert-danger alert-dismissible" role="alert">
				  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				  <strong>Warning!</strong> Invalid username or password!
				</div>
			<?php endif; ?>
			Username: 
			<input type="text" name="username" class="form-control"/></br>
			Password:
			<input type="password" name="password" class="form-control"/></br>
			<button type="submit" class="btn btn-lg btn-info"/>
				<span class="glyphicon glyphicon-send"></span> Submit
			</button>
		</form>
	</div>
</div>
