<div class="categories">
		<h4 class="title">Categories</h4>
			<a href="\onhand">Onhand Items</a></br>
			<a href="\soap">Soaps</a></br>
			<a href="\gadget">Gadgets</a></br>
			<a href="\bag">Bags</a></br>
			<a href="\dress">Dresses</a></br>
			<a href="\skirts">Shorts/Skirts/Denim</a></br>
			<a href="\pants">Pants/Jeggings/Harem Pants</a></br>
			<a href="\tops">Tops/Loose Tops</a></br>
			<a href="\pullovers">Pullovers/Longsleeves</a></br>
			<a href="\jackets">Jackets/Cardigans/Blazers</a></br>
			<a href="\jumpshorts">Jumpshorts/Jumpsuits</a></br>
</div>
<div class="cat-album">
		<h2 class="title">Onhand Items</h2>
		<p class="title">Available items onhand</p>
		<div class="pic-album">
			<?php
				$directory = "\images/onhand/";
				$files = glob($directory.'*.jpeg');
				if ($files !== false) {
					foreach ($files as $key => $value) {?>						
						<div class="picture" id="pants1">
						<img src="<?php echo $value?>" class="picture-inner"></br>
						<button id="p1" class="btn btn-sm btn-danger">Add to Cart</button>
					</div>
				<?php }}?>
		</div>
</div>
<script type="text/javascript">
function addToCart(){
	document.getElementById('pants1').innerHTML = "hello";
}
</script>