<div class="or-container">
	<div class="page-header">
		<h1>Order Form</h1></br>
		<CENTER>
			<span class="glyphicon glyphicon-pushpin"></span> Fixed Price</br>
			<span class="glyphicon glyphicon-remove"></span> NO RESERVATION 
			<span class="glyphicon glyphicon-remove"></span> NO MEET UPS 
			<span class="glyphicon glyphicon-remove"></span> NO BOGUS BUYERS (Photos will be poster)</br>
			<span class="glyphicon glyphicon-remove"></span> NO JOY RESERVERS (Photos will be poster)
			<span class="glyphicon glyphicon-remove"></span> NO SWAP
			<span class="glyphicon glyphicon-remove"></span> NO WORN PICTURES</br>
			<span class="glyphicon glyphicon-remove"></span> NO CANCELLATION OF ORDERS ONCE THE FORM IS SUBMITTED
		</CENTER>
	</div>
	<hr class="line hr">
	<div class="form">
			<form>
				First Name: <input type="text" name="fname" class="form-control"/>
				Last Name:  <input type="text" name="lname" class="form-control"/>
				MI:  <input type="text" name="mi" class="form-control"/></br>
				Address:<input type="text" name="address" class="form-control"/></br>
				Instagram Acct: <input type="text" name="ig" class="form-control"/></br>
				Facebook Acct: <input type="text" name="fb" class="form-control"/></br>
				Contact No.: <input type="text" name="cno" class="form-control"/></br>
				Mode of Payment:
				 <input type="radio" name="mop" class="radio-inline"/> BPI 
				 <input type="radio" name="mop" class="radio-inline"/> LBC
				 <input type="radio" name="mop" class="radio-inline"/> Cebuana 
				 <input type="radio" name="mop" class="radio-inline"/> Western
				 <input type="radio" name="mop" class="radio-inline"/> Palawan </br></br>
				Date of Payment: <input type="date" name="dop" class="space">
				<button class="btn btn-danger btn-lg">Submit Order</button>
			</form>
	</div>
</div>