<div class="or-container">
	<div class="page-header">
		<h1>Order Form</h1></br>
		<center>
			<h5>Cut Off  Every Friday!!</h5>
			<h6>PLEASE ALWAYS HAVE YOUR 2ND-3RD OPTION OF DESIGN/COLOR</h6>
			<span class="glyphicon glyphicon-pushpin"></span> Fixed Price</br>
			<span class="glyphicon glyphicon-remove"></span> NO RESERVATION 
			<span class="glyphicon glyphicon-remove"></span> NO CANCELLATION OF ORDERS 
			<span class="glyphicon glyphicon-remove"></span> NO MEET UPS </br>
			<span class="glyphicon glyphicon-remove"></span> NO BOGUS BUYERS (Photos will be posted)
			<span class="glyphicon glyphicon-remove"></span> NO JOY RESERVERS (Photos will be posted)</br>
			<span class="glyphicon glyphicon-remove"></span> NO SWAP
			<span class="glyphicon glyphicon-remove"></span> NO WORN PICTURES</br>
			<span class="glyphicon glyphicon-remove"></span> NO CANCELLATION OF ORDERS ONCE THE FORM IS SUBMITTED
		</center>
	</div>
	<hr class="line hr">
	<div class="form">
			<form method="post"> 		
				First Name: <input type="text" name="fname" class="form-control"/></br>
				Last Name:  <input type="text" name="lname" class="form-control"/></br>
				MI:  <input type="text" name="mi" class="form-control"/></br>
				Address:<input type="text" name="address" class="form-control"/></br>
				Instagram Acct: <input type="text" name="ig" class="form-control"/></br>
				Facebook Acct: <input type="text" name="fb" class="form-control"/></br>
				Contact No.: <input type="text" name="cno" class="form-control"/></br>
				Mode of Payment:
				 <input type="radio" name="mop" class="radio-inline" value="bpi"/> 
					<img src = "/images/bpi.jpg" class="mop"/>
				 <input type="radio" name="mop" class="radio-inline" value="lbc"/>
					<img src = "/images/cebuana.jpg" class="mop"/>
				 <input type="radio" name="mop" class="radio-inline" value="cebuana"/>
					<img src = "/images/lbc.jpg" class="mop"/></br>
				 <input type="radio" name="mop" class="radio-inline" value="western"/> 
					<img src = "/images/palawan.jpg" class="mop"/>
				 <input type="radio" name="mop" class="radio-inline" value="palawan"/>
					<img src = "/images/western.jpg" class="mop"/>
				</br>
				Date of Payment: <input type="date" name="dop" class="space"></br>
				<button class="btn btn-danger btn-lg" type="submit">
					<span class="glyphicon glyphicon-send"></span> Submit Order
				</button>
			</form>
	</div>
</div>