<div class="categories">
	<h4>Categories</h4>
	<a href="\pants">Pants</a></br>
	<a href="\skirts">Skirts</a></br>
	<a href="\dress">Dresses</a></br>
	<a href="\tops">Tops</a></br>
</div>
<div class="cat-album">
		<h2 class="title">Skirts</h2>
		<p class="title">Skater -- Corporate -- Pencil Cut</p>
		<div class="pic-album">
			<div class="picture" id="pants1">
				<img src="\images\s1.jpeg" class="picture-inner"></br>
				Size : S-M-L</br>
				<button id="p1" class="btn btn-sm btn-danger">Add to Cart</button>
			</div>
			<div class="picture" id="pants1">
				<img src="\images\s2.jpeg" class="picture-inner"></br>
				Size : S-M-L</br>
				<button id="p1" class="btn btn-sm btn-danger">Add to Cart</button>
			</div>
			<div class="picture" id="pants1">
				<img src="\images\s3.jpeg" class="picture-inner"></br>
				Size : S-M-L</br>
				<button id="p1" class="btn btn-sm btn-danger">Add to Cart</button>
			</div>
		</div>
</div>
<script type="text/javascript">
function addToCart(){
	document.getElementById('pants1').innerHTML = "hello";
}
</script>